version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: f1_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: f1_db
    ports:
      - "8080:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./sql/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U f1_user -d f1_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - f1_network

networks:
  f1_network:
    driver: bridge

volumes:
  postgres_data: 